[project]
name = "Zero"
authors = [ "Zero Day Code" ]

[compiler]
cpp_compiler = "clang"
cpp_standard = "20"
std_lib = "libc++"

[build]
output_dir = "./out"

[executable]
executable_name = "zero"
sources = [ "*.cpp" ]

[tests]
tests_executable_name = "zero_tests"
sources = [ "./zero/tests/**/*.cpp" ]

[modules]
base_ifcs_dir = "./zero/ifc"
interfaces = [
    { file = 'commons/typedefs.cppm' },    
    { file = 'types/type_info.cppm' },
    { file = 'commons/concepts.cppm', dependencies = ['typedefs'] },

    ### Iterator library
    { file = 'iterators/internal/iterator_detail.cpp', partition = { module = 'iterator', partition_name = 'detail' } },
    { file = 'iterators/iterator_concepts.cppm', partition = { module = 'iterator', partition_name = 'concepts' } },
    # Modern
    { file = 'iterators/iterator_facade.cppm', partition = { module = 'iterator' } },
    { file = 'iterators/input_iterator.cppm', partition = { module = 'iterator' } },
    # Legacy
    { file = 'iterators/legacy/legacy_iterator.cppm', partition = { module = 'iterator' } },
    { file = 'iterators/legacy/legacy_input_iterator.cppm', partition = { module = 'iterator' } },
    # Root
    { file = 'iterators/iterator.cppm' },

    # The collections/containers library
    { file = 'collections/container.cppm', dependencies = ['type_info'] },
    { file = 'collections/array.cppm', dependencies = ['typedefs', 'concepts', 'iterator', 'container'] },
    { file = 'collections/collections.cppm', dependencies = ['array'] },
    { file = 'zero.cppm', dependencies = ['collections'] }
]

gcc_sys_modules = ['cstdio']
